ForensicExpertCRM_Web/Models/Employee/EmployeeViewModel.cs
using ForensicExpertCRM_Web.Data.Domain;
using ForensicExpertCRM_Web.Models.Expert;

namespace ForensicExpertCRM_Web.Models.Employee
{
    public class EmployeeViewModel
    {
        public string Name { get; set; }

        public string Login { get; set; }

        public string Password { get; set; }

        public int EmployeeManagmentId { get; set; }

        //public List<EmployeeManagmentRadioBtnModel> EmployeeManagments { get; set; }


        public Data.Domain.Employee ToEntity()
        {
            var res = new Data.Domain.Employee()
            {
                Name = Name,
                Email = Login,
                PasswordHash = Password,
                EmployeeManagmentId = EmployeeManagmentId
                
                
            };
     
            return res;
        }
    }

    public class EmployeeManagmentRadioBtnModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsSelected { get; set; }
    }


    public static class EmployeeModelExtension
    {
        public static List<EmployeeManagmentRadioBtnModel> EmployeeManagmentToCheckBoxModel(this List<EmployeeManagment> typeExpertises)
        {
            var model = new List<EmployeeManagmentRadioBtnModel>();
            foreach (var type in typeExpertises)
            {
                model.Add(new EmployeeManagmentRadioBtnModel() { Id = type.Id, Name = type.Name, IsSelected = false });
            }
            return model;
        }

        public static List<EmployeeManagment> ToEntity(this List<EmployeeManagmentRadioBtnModel> expertManagmentRadioBtnModels)
        {
            var res = new List<EmployeeManagment>();
            foreach (var item in expertManagmentRadioBtnModels)
            {
                if (item.IsSelected == true)
                    res.Add(new EmployeeManagment()
                    {
                        Id = item.Id,
                        Name = item.Name

                    });
            }

            return res;
        }

    }
}

ForensicExpertCRM_Web/Controllers/EmployeeController.cs
using ForensicExpertCRM_Web.Data;
using ForensicExpertCRM_Web.Data.Domain;
using ForensicExpertCRM_Web.Models.Employee;
using ForensicExpertCRM_Web.Models.Expert;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ForensicExpertCRM_Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<MyUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly EmployeeRepository employeeRepository;
        public EmployeeController(ApplicationDbContext context, UserManager<MyUser> userManager, RoleManager<IdentityRole> roleManager, EmployeeRepository employeeRepository)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
            this.employeeRepository = employeeRepository;
        }
        public async Task<IActionResult> Index()
        {

            var returnValue = View(await _context.Employees.ToListAsync());

            return returnValue;
        }


        public async Task<IActionResult> Details(string? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var experts = await _context.Employees.Include(x => x.EmployeeManagment)
            .FirstOrDefaultAsync(m => m.Id == id.ToString());
            if (experts == null)
            {
                return NotFound();
            }

            return View(experts);
        }


        // GET: ExpertManagments/Create
        public IActionResult Create()
        {
            
            ViewBag.EmployeeManagments = _context.EmployeeManagments.ToList();
            return View();
        }

        // POST: ExpertManagments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                await employeeRepository.CreateAsync(employee.ToEntity(), employee.Login, employee.Password);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.EmployeeManagments = _context.EmployeeManagments.ToList();
            return View(employee);
        }

    }
}

ForensicExpertCRM_Web/Controllers/EmployeeManagmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ForensicExpertCRM_Web.Data;
using ForensicExpertCRM_Web.Data.Domain;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace ForensicExpertCRM_Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class EmployeeManagmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployeeManagmentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: EmployeeManagments
        public async Task<IActionResult> Index()
        {
            return _context.EmployeeManagments != null ?
                        View(await _context.EmployeeManagments.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.EmployeeManagments'  is null.");
        }

        // GET: EmployeeManagments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.EmployeeManagments == null)
            {
                return NotFound();
            }

            var employeeManagment = await _context.EmployeeManagments
                .Include(x => x.Employees)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employeeManagment == null)
            {
                return NotFound();
            }

            return View(employeeManagment);
        }

        // GET: EmployeeManagments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EmployeeManagments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address")] EmployeeManagment employeeManagment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employeeManagment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employeeManagment);
        }

        // GET: EmployeeManagments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.EmployeeManagments == null)
            {
                return NotFound();
            }

            var employeeManagment = await _context.EmployeeManagments.FindAsync(id);
            if (employeeManagment == null)
            {
                return NotFound();
            }
            return View(employeeManagment);
        }

        // POST: EmployeeManagments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address")] EmployeeManagment employeeManagment)
        {
            if (id != employeeManagment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employeeManagment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeManagmentExists(employeeManagment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employeeManagment);
        }

        // GET: EmployeeManagments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.EmployeeManagments == null)
            {
                return NotFound();
            }

            var employeeManagment = await _context.EmployeeManagments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employeeManagment == null)
            {
                return NotFound();
            }

            return View(employeeManagment);
        }

        // POST: EmployeeManagments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.EmployeeManagments == null)
            {
                return Problem("Entity set 'ApplicationDbContext.EmployeeManagments'  is null.");
            }
            var employeeManagment = await _context.EmployeeManagments.FindAsync(id);
            if (employeeManagment != null)
            {
                _context.EmployeeManagments.Remove(employeeManagment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeManagmentExists(int id)
        {
            return (_context.EmployeeManagments?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ForensicExpertCRM_Web/Views/Employee/Create.cshtml
@using ForensicExpertCRM_Web.Models.Employee;
@model EmployeeViewModel

@{
    ViewData["Title"] = "Создать";
}

<h1 align="center">Создать сотрудника</h1>
<hr />
<div>

    <form asp-action="Create" asp-controller="Employee" id="CreateForm">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="create">
            <div class="create-item">
                <div class="create-label control-label">
                    Имя
                </div>

                <div class="create-input ">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>





            <div class="create-item">

                <div class="create-input check-box-list">
                    @{
                        var expertManagment = ViewBag.EmployeeManagments as List<EmployeeManagment>;

                        <label class="form-label">Выберите подразделение:</label>
                        <select class="form-select" asp-for="EmployeeManagmentId">
                            @{
                                foreach (var item in expertManagment)
                                {
                                    <option value="@item.Id">@item.Name</option>
                                }
                            }
                        </select>
                    }
                </div>

                <div class="create-item">
                    <div class="create-label control-label">
                        Логин
                    </div>

                    <div class="create-input">
                        <input asp-for="Login" class="form-control" />
                        <span asp-validation-for="Login" class="text-danger"></span>
                    </div>
                </div>

                <div class="create-item">
                    <div class="create-label control-label">
                        Пароль
                    </div>

                    <div class="create-input">
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>

            </div>


            <hr />
            <input type="submit" class="btn btn-primary w-100" value="Создать" />
        </div>
    </form>
</div>

@section scripts {

    <script type="text/javascript">

        $('form').eq(0).on("change", function (e) {
            console.log("change");
            target = e.target;
            console.log(target);
            console.log(target.getAttribute("expertmangament"));
            if (target.getAttribute("expertmangament") == null) return;

            $('input[expertmangament]').each(function () {

                if (e.target != this)
                    this.checked = false;
            });
        })

                //$('form').eq(0).on('submit', function () {
                //    return $('input[name^=field]:checked:enabled').length == 1;
                //});
    </script>

}

ForensicExpertCRM_Web/Views/Employee/Details.cshtml
@model Employee

@{
    ViewData["Title"] = "Сотрудник";
}

<h1 align="center">Сотрудник</h1>

<div>
    <hr />
    <div class="details">
        <div class="details-item">
            <div class="details-item-label">
                Имя
            </div>

            <div class="details-item-value">
                @Model.Name
            </div>

            <br />

            <div class="details-item-label">
                Название подразделения
            </div>

            <div class="details-item-value">
                <a asp-action="Details" asp-controller="EmployeeManagments" asp-route-Id="@Model.EmployeeManagment.Id">@Model.EmployeeManagment.Name</a>
            </div>
        </div>
        <hr />

    </div>


</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Изменить</a> |
    <a asp-action="Index">Вернуться к списку</a>
</div>

ForensicExpertCRM_Web/Views/Employee/Index.cshtml
@model List<Employee>

@{
    ViewData["Title"] = "Сотрудники";
}

<div align="center">
    <h1>Сотрудники</h1>
    <a asp-action="Create">Создать сотрудника</a>
</div>

<div class="list mt-1">

    @*Заголовок*@
    <br />

    <div class="list-item">
        <div class="list-item-col">
            Имя
        </div>
        <div class="list-item-col">
            Логин
        </div>

        <div class="list-item-col">
            Действия
        </div>
    </div>
    <hr />


    @*Тело*@
    @{
        foreach (var item in Model)
        {
            <div class="list-item">
                <div class="list-item-col">
                    @item.Name
                </div>

                <div class="list-item-col">
                    @item.Email
                </div>

                <div class="list-item-col">
                    <a asp-controller="Employee" asp-action="Edit" asp-route-id="@item.Id">Изменить</a> |
                    <a asp-controller="Employee" asp-action="Details" asp-route-id="@item.Id">Подробнее</a> |
                    <a asp-controller="Employee" asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
                </div>
            </div>
            <hr />
        }
    }

</div>