ForensicExpertCRM_Web/Models/Expert/ExpertViewModel.cs
using ForensicExpertCRM_Web.Data.Domain;

namespace ForensicExpertCRM_Web.Models.Expert
{
    public class ExpertViewModel
    {
        public string Name { get; set; }


        public int Rating { get; set; }

        public string Login { get; set; }

        public string Password { get; set; }

        public int ExpertManagmentId { get; set; }

        public List<TypeExpertiseCheckBoxModel> TypesExpertise { get; set; }

        //public List<ExpertManagmentRadioBtnModel> ExpertManagments { get; set; }


        public Data.Domain.Expert ToEntity()
        {
            var res = new Data.Domain.Expert()
            {
                Rating = Rating,
                Name = Name,
                TypesExpertise = TypesExpertise.ToEntity(),
                Email = Login,
                PasswordHash = Password
            };

            return res;
        }

    }

    public class TypeExpertiseCheckBoxModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsChecked { get; set; }


    }

    public class ExpertManagmentRadioBtnModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsSelected { get; set; }
    }


    public static class ExpertModelExtension
    {
        public static List<TypeExpertiseCheckBoxModel> TypesExpertiseToCheckBoxModel(this List<TypeExpertise> typeExpertises)
        {
            var model = new List<TypeExpertiseCheckBoxModel>();
            foreach (var type in typeExpertises)
            {
                model.Add(new TypeExpertiseCheckBoxModel() { Id = type.Id, Name = type.Name, IsChecked = false });
            }
            return model;
        }


        public static List<ExpertManagmentRadioBtnModel> ExpertManagmentToCheckBoxModel(this List<ExpertManagment> typeExpertises)
        {
            var model = new List<ExpertManagmentRadioBtnModel>();
            foreach (var type in typeExpertises)
            {
                model.Add(new ExpertManagmentRadioBtnModel() { Id = type.Id, Name = type.Name, IsSelected = false });
            }
            return model;
        }

        public static List<ExpertManagment> ToEntity(this List<ExpertManagmentRadioBtnModel> expertManagmentRadioBtnModels)
        {
            var res = new List<ExpertManagment>();
            foreach (var item in expertManagmentRadioBtnModels)
            {
                if (item.IsSelected == true)
                    res.Add(new ExpertManagment()
                    {
                        Id = item.Id,
                        Name = item.Name

                    });
            }

            return res;
        }
        public static List<TypeExpertise> ToEntity(this List<TypeExpertiseCheckBoxModel> typeExpertiseModel)
        {
            var res = new List<TypeExpertise>();
            foreach (var item in typeExpertiseModel)
            {
                if (item.IsChecked == true)
                    res.Add(new TypeExpertise()
                    {
                        Id = item.Id,
                        Name = item.Name

                    });
            }

            return res;
        }
    }


}

ForensicExpertCRM_Web/Controllers/ExpertController.cs
using ForensicExpertCRM_Web.Data;
using ForensicExpertCRM_Web.Data.Domain;
using ForensicExpertCRM_Web.Models.Expert;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using Test_OP_Web;

namespace ForensicExpertCRM_Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class ExpertController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<MyUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ExpertRepository _expertRepository;
        public ExpertController(ApplicationDbContext context, UserManager<MyUser> userManager, RoleManager<IdentityRole> roleManager, ExpertRepository expertRepository)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _expertRepository = expertRepository;
        }
        public async Task<IActionResult> Index()
        {

            var returnValue = View(await _context.Experts.ToListAsync());
            return returnValue;
        }


        public async Task<IActionResult> Details(string? id)
        {
            if (id == null || _context.Experts == null)
            {
                return NotFound();
            }

            var experts = await _context.Experts
                .Include(x => x.ExpertManagment)
                .Include(x => x.TypesExpertise)
                .FirstOrDefaultAsync(m => m.Id == id.ToString());
            if (experts == null)
            {
                return NotFound();
            }

            return View(experts);
        }


        // GET: ExpertManagments/Create
        public IActionResult Create()
        {
            ViewBag.ExpertManagments = _context.ExpertManagments.ToList().ExpertManagmentToCheckBoxModel();
            ViewBag.TypeExpertise = _context.TypesExpertise.ToList().TypesExpertiseToCheckBoxModel();
            return View();
        }

        // POST: ExpertManagments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ExpertViewModel expert)
        {
            if (ModelState.IsValid)
            {
                var expertEntity = expert.ToEntity();
                expertEntity.ExpertManagment = await _context.ExpertManagments.FirstOrDefaultAsync(x => x.Id == expert.ExpertManagmentId);
                await _expertRepository.AddExpertAsync(expertEntity , expert.Login, expert.Password);
                return RedirectToAction(nameof(Index));
            }

            ViewBag.ExpertManagments = _context.ExpertManagments.ToList().ExpertManagmentToCheckBoxModel();
            ViewBag.TypeExpertise = _context.TypesExpertise.ToList().TypesExpertiseToCheckBoxModel();
            return View(expert);
        }

    }
}

ForensicExpertCRM_Web/Controllers/ExpertManagmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ForensicExpertCRM_Web.Data;
using ForensicExpertCRM_Web.Data.Domain;
using Microsoft.AspNetCore.Authorization;

namespace ForensicExpertCRM_Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class ExpertManagmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ExpertManagmentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ExpertManagments
        public async Task<IActionResult> Index()
        {
              return _context.ExpertManagments != null ? 
                          View(await _context.ExpertManagments.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.ExpertManagments'  is null.");
        }

        // GET: ExpertManagments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ExpertManagments == null)
            {
                return NotFound();
            }

            var expertManagment = await _context.ExpertManagments.Include(x=>x.Experts)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (expertManagment == null)
            {
                return NotFound();
            }

            return View(expertManagment);
        }

        // GET: ExpertManagments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ExpertManagments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address")] ExpertManagment expertManagment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(expertManagment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(expertManagment);
        }

        // GET: ExpertManagments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ExpertManagments == null)
            {
                return NotFound();
            }

            var expertManagment = await _context.ExpertManagments.FindAsync(id);
            if (expertManagment == null)
            {
                return NotFound();
            }
            return View(expertManagment);
        }

        // POST: ExpertManagments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address")] ExpertManagment expertManagment)
        {
            if (id != expertManagment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(expertManagment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpertManagmentExists(expertManagment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(expertManagment);
        }

        // GET: ExpertManagments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ExpertManagments == null)
            {
                return NotFound();
            }

            var expertManagment = await _context.ExpertManagments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (expertManagment == null)
            {
                return NotFound();
            }

            return View(expertManagment);
        }

        // POST: ExpertManagments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ExpertManagments == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ExpertManagments'  is null.");
            }
            var expertManagment = await _context.ExpertManagments.FindAsync(id);
            if (expertManagment != null)
            {
                _context.ExpertManagments.Remove(expertManagment);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExpertManagmentExists(int id)
        {
          return (_context.ExpertManagments?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ForensicExpertCRM_Web/Views/Expert/Create.cshtml
@using ForensicExpertCRM_Web.Models.Expert;
@model ExpertViewModel

@{
    ViewData["Title"] = "Создать";
}

<h1>Создать эксперта</h1>
<a asp-action="Create">Создать эксперта</a>
<div>

    <form asp-action="Create" asp-controller="Expert" id="CreateForm">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="create">
            <div class="create-item">
                <div class="create-label control-label">
                    Имя
                </div>

                <div class="create-input ">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>


            <div class="create-item">
                <div class="create-label control-label">
                    Рэйтинг
                </div>

                <div class="create-input">
                    <input asp-for="Rating" class="form-control" />
                    <span asp-validation-for="Rating" class="text-danger"></span>
                </div>
            </div>


            <div class="create-item">
                <div class="create-label control-label">
                    Тип экспертизы
                </div>

                <div class="create-input check-box-list">
                    @{
                        var typeExpertise = ViewBag.TypeExpertise as List<TypeExpertiseCheckBoxModel>;
                        if (typeExpertise == null) typeExpertise = Model.TypesExpertise;

                        for (int i = 0; i < typeExpertise.Count; i++)
                        {
                            <div class="check-box-item">
                                <input class="form-check-input" type="checkbox" asp-for="TypesExpertise[i].IsChecked" />
                                <label class="form-check-label" asp-for="@Model.TypesExpertise[i].IsChecked">@typeExpertise[i].Name</label>
                                <input type="hidden" asp-for="@Model.TypesExpertise[i].Id" value="@typeExpertise[i].Id" />
                                <input type="hidden" asp-for="@Model.TypesExpertise[i].Name" value="@typeExpertise[i].Name" />
                            </div>
                        }
                    }
                </div>
            </div>


            <div class="create-item">
                <div class="create-label control-label">
                    Подразделение
                </div>

                <div class="create-input check-box-list">
                    @{

                        var expertManagment = ViewBag.ExpertManagments as List<ExpertManagmentRadioBtnModel>;


                        <label class="form-label">Выберите подразделение:</label>
                        <select class="form-select" asp-for="ExpertManagmentId">
                            @{
                                foreach (var item in expertManagment)
                                {
                                    <option value="@item.Id">@item.Name</option>
                                }
                            }
                        </select>
                    }
                </div>


                <div class="create-item">
                    <div class="create-label control-label">
                        Логин
                    </div>

                    <div class="create-input">
                        <input asp-for="Login" class="form-control" />
                        <span asp-validation-for="Login" class="text-danger"></span>
                    </div>
                </div>

                <div class="create-item">
                    <div class="create-label control-label">
                        Пароль
                    </div>

                    <div class="create-input">
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>

            </div>



            <input type="submit" class="btn btn-primary m-1" />
        </div>
    </form>
</div>

@section scripts {

    <script type="text/javascript">

        $('form').eq(0).on("change", function (e) {
            console.log("change");
            target = e.target;
            console.log(target);
            console.log(target.getAttribute("expertmangament"));
            if (target.getAttribute("expertmangament") == null) return;

            $('input[expertmangament]').each(function () {

                if (e.target != this)
                    this.checked = false;
            });
        })

    </script>
}

ForensicExpertCRM_Web/Views/Expert/Details.cshtml
@model Expert

@{
    ViewData["Title"] = "Эксперт";
}

<h1 align="center">Эксперт</h1>

<div>
    <hr />
    <div class="details">
        <div class="details-item">
            <div class="details-item-label">
                Имя
            </div>

            <div class="details-item-value">
                @Model.Name
            </div>
        </div>

        <div class="details-item">
            <div class="details-item-label">
                Подразделение
            </div>

            <div class="details-item-value">
                <a asp-action="Details" asp-controller="ExpertManagments" asp-route-Id="@Model.ExpertManagment.Id">@Model.ExpertManagment.Name</a>
            </div>
        </div>

        <div class="details-item">
            <div class="details-item-label">
                Рэйтинг
            </div>

            <div class="details-item-value">
                @Model.Rating
            </div>
        </div>

      


        <div class="details-item">
            <div class="details-item-label">
                Виды эспертизы
            </div>
            @foreach (var typeExpertise in Model.TypesExpertise)
            {
                <div class="">
                    @typeExpertise.Name
                </div>
            }
        </div>

    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Изменить</a> |
    <a asp-action="Index">Вернуться к списку</a>
</div>

ForensicExpertCRM_Web/Views/Expert/Index.cshtml
@model List<Expert>

@{
    ViewData["Title"] = "Эксперты";
}


<div class="list">

    @*Заголовок*@

    <div class="list-item">
        <div class="list-item-col">
            Имя
        </div>
        <div class="list-item-col">
            Логин
        </div>

        <div class="list-item-col">
            Рэйтинг
        </div>

        <div class="list-item-col">
            Кнопки
        </div>
    </div>


    @*Тело*@
    @{
        foreach (var item in Model)
        {
            <div class="list-item">
                <div class="list-item-col">
                    @item.Name
                </div>

                <div class="list-item-col">
                    @item.Email
                </div>

                <div class="list-item-col">
                    @item.Rating
                </div>


                <div class="list-item-col">
                    <a asp-action="Edit" asp-route-id="@item.Id">Изменить</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Подробнее</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
                </div>
            </div>
            <hr />
        }
    }

</div>